### ISSUE TITLE
types for all members

### ISSUE THREAD

**Issue by crookse** [drashland/deno-drash#115]
## Summary

What: All members in the Drash namespace should have a type associations.

Why: Stricter syntax, more explosions when bad code is introduced, better API Reference page output.

**_This work requires [deno-drash-docs](https://github.com/drashland/deno-drash-docs) to be recompiled. See deno-drash-docs' [Workflows](https://github.com/drashland/deno-drash-docs/blob/master/WORKFLOWS.md) for committing changes to deno-drash-docs._**

## Acceptance Criteria

- [x] all members have types where possible
- [x] tests pass (`console/tests`)
- [x] [deno-drash-docs](https://github.com/drashland/deno-drash-docs) API Reference page recompiled to reflect added types
  - [x] update `deno-drash` version in `package.json` to reflect tag used for this work
  - [x] make pull request to `staging` branch; verify work https://drash.land/staging

**Comment by ebebbington** [comment]
Can this still be picked up by someone? Might look into it myself

**Comment by crookse** [comment]
@ebebbington ,

Go for it

**Comment by ebebbington** [comment]
Ok cheers, I don't suppose you could give an example of a member? E.g. does this include parameters, general use variables etc etc

**Comment by player-4** [comment]
hey @ebebbington, the server is a good example of having members that need types. below is what `Drash.Http.Server` constructor looks like:

```typescript
constructor(configs: any) {
  ....
}
```

`any` is invalid and should be something like `ServerConfigs`. and that could look something like

```typescript
interface ServerConfigs {
    resources: Drash.Http.Resource[];
    address?: string;
}
```

there are a lot of places in the codebase that state `any` and they shouldn't. some methods don't even have types associated so people can pass in anything and drash would be like, "ok. yea. that looks good to me."

**Comment by ebebbington** [comment]
Sonds good to me, is it worth adding types to functions that are missing them at the same time?

E.g. I've seen a few examples:

**Comment by player-4** [comment]
yes. just make sure they're justifiable. also, you might see `request: any`. don't change that. `any` is intentional because drash doesn't care what `request` object is passed in. it can be the `ServerRequest` object  from deno, or a transformed `ServerRequest` object. it doesn't and shouldn't discriminate `request` objects.

**Comment by ebebbington** [comment]
Understandable, I assumed the `request` object is **way too dynamic** to type

**Comment by ebebbington** [comment]
Can I just clarify if ConsoleLogger and FileLogger can use the LoggerConfigs interface?

**Comment by player-4** [comment]
yea. forgot we already had that. yea do it. and it does make sense to make them optional. off the top of my head i don't remember which configs are required.

**Comment by ebebbington** [comment]
Ok ill dig deeper into it to make the interface robust

**Comment by ebebbington** [comment]
Inside `src/http/server.ts`, the following property inside the ServerConfigs interface seems to throw the following when i run `deno ... tests/http/middleware_test.js`:

```
error TS2322: Type 'typeof ResourceWithMiddlewareHooked' is not assignable to type 'Resource'.

► file:///D:/Development/environments/deno-drash/tests/unit/http/middleware_test.ts:297:17

297     resources: [ResourceWithMiddlewareHooked]
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  Did you mean to use 'new' with this expression?

    ► file:///D:/Development/environments/deno-drash/tests/unit/http/middleware_test.ts:297:17

    297     resources: [ResourceWithMiddlewareHooked]
```

Seems to be, because the ServerConfig is set up like so:
*(Note how i have modified the `resources` property)*
```
interface ServerConfigs {
  resources: Drash.Http.Resource[],
  address?: string,
  middleware?: any,
  logger?: Drash.CoreLoggers.ConsoleLogger | Drash.CoreLoggers.FileLogger,
  memory_allocation?: { multipart_form_data?: number },
  static_paths?: string[],
  directory?: string,
  response_output?: string,
  resource_level?: any,
  server_level?: any
}
```

Yet inside `tests/unit/http/middleware_test.ts`, we have the following declation to test:
*(Note the `resources` line)*
```
let server = new members.MockServer({
    ...
    resources: [ResourceWithMiddleware]
  });
```

So if I check `ResourcesWithMiddleware`, i see it doesn't implement `Drash.Http.Resource`, but `member.Drash.Http.Resource`:

```
// tests/http/middleware_test.ts:317
class ResourceWithMiddleware extends members.Drash.Http.Resource {
```

So i'm guessing it's throwing an error because the `ResourcesWithMiddleware` is passing in the correct resource to the `ServerConfigs`

Any ideas? Setting `resources: any` fixes it, but not ideal

**Comment by player-4** [comment]
that's strange. `members.Drash.Http.Resource` is `Drash.Http.Resource`. i would say do `any` for now and come back to it as long as the tests are still passing. `any` is not ideal, but having the other types in place put drash in a better position

**Comment by player-4** [comment]
does `ResourceWithMiddlewareHooked` extend `members.Drash.Http.Resource` ? i noticed you mentioned two different resources:

`ResourceWithMiddlewareHooked`
and
`ResourceWithMiddleware`

**Comment by ebebbington** [comment]
Alright, i'll make a seperate issue soon to keep it tracked.

Actually here's some more info if it helps solving it now:
*(Note the `error` line)*
```
PS D:\Development\environments\deno-drash> deno test --allow-env --allow-net .\tests\unit\http\middleware_test.ts
Compile file:///D:/Development/environments/deno-drash/.deno.test.ts
error TS2739: Type 'typeof ResourceWithMiddleware' is missing the following properties from type 'Resource': request, response, server

► file:///D:/Development/environments/deno-drash/tests/unit/http/middleware_test.ts:19:17

19     resources: [ResourceWithMiddleware]
```

**Comment by player-4** [comment]
ok, that is strange. i see the issue, but don't know why the compiler is complaining. also, we use `console/tests` to run the tests so you don't have to test single files (unless you want to)

**Comment by ebebbington** [comment]
🤦‍♂  Ok, i'm not used to having a single test file that runs all other test files :P I'll run the `test.ts` to be sure, update any changes made from the `src` dir into their respective test files, test again and should be ready to go. Though i'm going to have to raise an issue until i can test :X

**Comment by crookse** [comment]
That's something I implemented when I first started Drash and saw the testing deno_std module. However, I might make an issue that gets away from using `console/tests` and have a script that runs `deno test` or a file that uses `Deno.run()`. Idk. It's up in the air right now. Btw thanks for contributing! You raised some pretty good issues.

**Comment by ebebbington** [comment]
It's a good idea tbf, I usually ran every route test one by one as a full blown integration test without even thinking about having a single file to tes them all.

Happy to contribute, started making a project using Deno and Drash a few weeks ago and I got really interested into both of them

The codebase is gawjus

**Comment by ebebbington** [comment]
All tests passed 🎉 Last question for clarify:

1. How would I go about recompiling the API ref page? I couldn't see anything specifically about this in the README, and I don't know if I'll be able to as I'm running Windows (have NPM installed and can get Python installed but i'm not so sure about yarn :P)

The i'll make the PR

**Comment by crookse** [comment]
That's great!! The API Reference page is built using `npm run dev` in `deno-drash-docs` repo. It doesn't use yarn.

Once you've run `npm run dev`, you can launch the docs in the browser and do your checks on content. I have seen some issues raised when others have tried cloning the repo. I tried cloning the repo and ran into some issues on another computer and made a Troubleshooting section in the doc's repo's README. Let me know if it works for you. I'm here to help!

**Comment by ebebbington** [comment]
I'm having real problems trying to get the server up (environmental), had to end up getting Ubuntu SS and even then i'm getting every error in the world (NPM, watchmedo, sass, webpack :P)

Don't suppose if i push my branch up that someone can test it for me? I can tell by the errors this would be way faster

**Comment by player-4** [comment]
i can do it for you. maybe eric can merge it later and deploy the docs to the staging env and we can all do checks on content

**Comment by ebebbington** [comment]
Ok cool, i'm not too sure how to approach this process though - would a cherrypick even work from a forked repo then make a PR once it's checked? Or the main repo create a temp branch for me to make a PR to?

**Comment by player-4** [comment]
we're actually in the process of switching this process up, so you're the first to give it a shot. congrats! lol

make a PR to `release/v0.33.1` branch

**Comment by ebebbington** [comment]
Lol i'm honored :P
