### ISSUE TITLE
parsing of request body causes “Cannot read property 'byteLength' of undefined” error

### ISSUE THREAD

**Issue by job111lyckk1** [drashland/deno-drash#122]
POST http://127.0.0.1:1447

version: drash v0.28.2

error: Uncaught TypeError: Cannot read property 'byteLength' of undefined
► bufio.ts:123:35

123     let rr: number | Deno.EOF = p.byteLength;

**Comment by crookse** [comment]
Hi @job111lyckk1,

Were you following a tutorial? If not, could you please provide the steps to reproduce the issue. Thanks!

**Comment by job111lyckk1** [comment]
Yes，I run a POST request according to the following example: http://drash.land/#/tutorials/servers/creating-a-server

`error: Uncaught TypeError: Cannot read property 'byteLength' of undefined
► bufio.ts:123:35

123     let rr: number | Deno.EOF = p.byteLength;
                                      ^

    at read (bufio.ts:123:35)
    at _bodyStream (server.ts:177:29)`

**Comment by crookse** [comment]
Have you tried making a `POST` to `localhost:1447` instead of `127.0.0.1:1447` ?

I ask because although in some frameworks `localhost` and `127.0.0.1` resolve to the same domain, I've noticed that deno doesn't do the same.

**Comment by crookse** [comment]
A workaround for could be added when `Drash.Http.Server.run()` is called, but I haven't felt the need for one. Also, I'd have to look at deno to see if they're mapping `localhost` to `127.0.0.1` manually. Otherwise you'd have to do this to get `127.0.0.1` to work:

```typescript
let server = new Drash.Http.Server({
  address: "127.0.0.1:1447",
  response_output: "text/html",
  resources: [SomeResource]
});
```

**Comment by job111lyckk1** [comment]
Both `localhost` and `127.0.0.1` will report an error.

**Comment by crookse** [comment]
So I did discover something. Apparently Postman is causing Drash (or deno) to error out now. When I start the server and use `curl`, everything works fine. Not sure what's going on with Postman. Here is what I ran with curl:

```
curl -X PUT http://localhost:1447
"PUT request received!"

curl -X POST http://localhost:1447
"POST request received!"

curl -X GET http://localhost:1447
"GET request received!"

curl -X PATCH http://localhost:1447
"Method Not Allowed"
```

I'll have to spend some time debugging Postman and why it's causing the errors.

**Comment by job111lyckk1** [comment]
I just tried curl and it works fine with all requests. postman only supports` GET` requests, but not `POST` `PUT` `DELETE`

**Comment by crookse** [comment]
@job111lyckk1,

I investigated the issue. Turns out Drash wasn't able to read request bodies since v0.28.1. Drash v0.28.1 addressed the following deno fix: https://github.com/denoland/deno/pull/3575. That fix makes `request.body` a reader. I'll have to run some tests against [`Drash.Services.HttpService. getHttpRequestBodyParsed()`](https://github.com/drashland/deno-drash/blob/master/src/services/http_service.ts#L34) and how it reads request bodies.

**Comment by crookse** [comment]
@job111lyckk1,

See release v0.28.3. Fix is in place.
