### ISSUE TITLE
Drash.Http.Server.redirect();

### ISSUE THREAD

**Issue by crookse** [drashland/deno-drash#142]
Please view https://github.com/drashland/deno-drash/blob/master/DEV.md before starting.

## Summary

What: Handle redirects

Why: Currently, Drash doesn't have any type of redirect feature. Although users can send a response with a redirect status code, it'd be much more convenient if the server handled that for them.

## Acceptance Criteria

- [x] documentation on handling redirects. This should fall under the Misc section.
- [x] tests
- [x] `server.redirect` should redirect to the specified location with the specified status code (see below)

## Example Pseudo Code (for implementation)

```typescript
server.redirect(httpStatusCode: number, location: string) { ... }
```

**Comment by saragee3** [comment]
Assigning this to myself. I can take a look sometime this week.
