### ISSUE TITLE
Cookie handling

### ISSUE THREAD

**Issue by crookse** [drashland/deno-drash#143]
Please view https://github.com/drashland/deno-drash/blob/master/DEV.md before starting.

## Summary

What: Handle cookies.

Why: Cookies are part of the request-resource-response lifecycle, but the Drash server doesn't handle them yet.

## Acceptance Criteria

- [x] documentation (should be under the Misc section and it should reference https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies)
- [x] tests
- [x] ~cookie schema matches schema in MDN~
- [x] use `Cookie` interface that Deno has defined
- [x] ~resources should be able to call `this.server.getCookie()` and `this.server.setCookie()`.~
- [x] resources should be able to get cookies from the request. the `HttpRequestService` should be the class that handles parsing cookies; and resources should be able to call `this.request.getCookie()` or something similar that makes sense
- [x] resources should be able to set cookies on the response (e.g., `this.response.setCookie()` or something similar that makes sense)
- [x] ~build `api_reference.json` file and update `deno-drash-docs` to use it.~

## Example Pseudo Code (for implementation)

```typescript
server.setCookie();
server.getCookie();
```
The methods above should implement https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies as closely as possible

**Comment by ebebbington** [comment]
I was thinking of taking this on and came to a conclusion on how this could be implemented:

The `this.request.headers.*` is always undfined so I can't try the `cookie` property (not sure how it's accessed in Drash, assuming there's another way but i'm testing in my own application that uses Drash as the Server), but the cookies come in look like a string e.g.: `cookiename=cookieval; cookiename2=cookieval2`, so assuming this, we could create a `cookies` property on the `Request` or `Server` class:
```
public cookies: [{name: string, value: string}]
```

Very early in the lifecycle, we can extract the cookies from the request like so:
```
public extractRequestCookies () {
 const splitCookies = this.request.headers.cookie.split(';')
 splitCookies.forEach(cookie => {
    this.request.cookies.push({name: cookie.split('=')[0], value: cookie.split('=')[1]
 })
}
```

Now we can create out getter and setter:

```
public setCookie({name: string, value: string}): void {
  this.request.cookies.push({name: name, value: value);
  // fixme :: will actually need to set it in the `headers` property
}
public getCookie (cookieName: string): string|boolean {
  let foundCokie ;
  this.request.cookies.forEach((cookie: Cookie) => {
    if (cookie.name === cookieName) {
      foundCookie = cookie
      break
    }
  })
  if (foundCookie) return foundCookie.value
  if (!foundCookie) return false
}
```

This might actually add a bunch of unrequired logic, so maybe just modifying the `headers.cookie` property is sufficient enough instead of controlling the new `cookies` property

**Comment by saragee3** [comment]
This is a good start! In additional, we definitely need to keep in mind: expiry, path, size, HTTPOnly, Secure, and SameSite properties for each cookie. Not sure if we can create sub issues, but I think it would be beneficial to break this out to not bloat this PR.

**Comment by crookse** [comment]
@ebebbington / @saragee3 ,

Deno has a cookie module that we can leverage (maybe). Documentation on it is skim, but I think we can figure out how to use it sufficiently without making our own getters and setters. Also, one of the services has a parser for “key=value” strings. It turns the string into an object. We can def reuse that and make it more generic. That is unless a new method would make more sense to keep methods from doing too much.

Just let me know who wants to take this and I’ll assign it. I’m going to be writing documentation today, so I’ll be in deno-drash-docs. Going to try to fix the CI.

**Comment by ebebbington** [comment]
Here's the module with the cookie interface and all the docs: https://deno.land/std/http/cookie.ts

How to integrate getting and setting (assuming you still want it in the server class):
```
import { getCookies, setCookie, delCookie, Cookie } from "https://deno.land/std/http/cookie.ts"
class Server ... {

  /*
   * @param request The request object e.g. this.getCookies(this.request)
  * @return cookie
  */
  public getCookies - getCookies

  /*
  * @param res The response object
  * @param cookie Object implementing the cookie interface
  */
  public setCookie = setCookie

  /*
   * @param res Response object
   * @param cookie name
   */
  public delCookie = delCookie
```

**Examples**
(Lets just say I did `document.cookie = "username=John Doe; expires=Thu, 18 Dec 2013 12:00:00 UTC";` on the client before hand)
```
// Inside some GET method of a resource somewhere
const cookies = this.server.getCookies(this.request) // { username: 'John Doe' } e.g. propname = cookiename, propval = cookie val
const newCookieOptions: Cookie = {
  name: 'car',
  value: 'Ford',
  ...
}
this.server.setCookie(this.response, newCookieOptions) // void, can't access cookie until next request
this.server.delCookie(this.response, 'car') // void
```

Testing in a working Drash environment, though there doesn't seem to be a way to get a specific cookie unless you call `getCookies` first, and manually loop through the returned object, e.g.:

```
//public getCookies = getCookies
public getCookie (name: string): string {
  let cookieValue = ''
  Object.keys(getCookies(this.request)).forEach((cookiename: string, cookieval: string) => {
    if (cookiename === name) cookieValue = cookieval
  })
  return cookieValue
}
```

I'll take this on if no one has by tomorrow night

**Comment by saragee3** [comment]
@ebebbington nice! looks like you got a good handle on this. thanks for doing the necessary research. Regarding `getCookie`, couldn't we just access the object directly?

```
//public getCookies = getCookies
public getCookie (name: string): string {
  let cookieValue = ''
  const cookies = getCookies(this.request));
  // cookies[name]
  return cookieValue
}
```

also, how does `forEach` work with `cookieval: string` as the second param? I'll assign it over to you! 💪

**Comment by ebebbington** [comment]
Absolutely, I didn't even think about doing it that way! I'll use that approach then.

Also (i'm now doubting myself :P) `Object.keys(someObject).forEach` will provide 2 values, the property name and the property value, take the following example:
```
const me = { name: 'Edward', username: 'ebebbington' }
Object.keys(me).forEach((propname, propval) => {
  console.log(propname) // 'name', then 'username'
  console.log(propval) // 'Edward', then 'ebebbington'
})
```

**Comment by ebebbington** [comment]
Added the code locally and all works well, where do I find `api_reference.json`? And i'm worried i'm gonna have problems again building `deno-drash-docs` :/ But i'll give it another try later tonight

**Comment by saragee3** [comment]
The second param in `forEach` is the iterator.

```
const me = { name: 'Edward', username: 'ebebbington' }
Object.keys(me).forEach((propname, propval) => {
  console.log(propname) // 'name', then 0
  console.log(propval) // 'Edward', then 1
});
```

I'm definitely not as familiar with the deno-drash-docs, but sure @crookse can help out :)

**Comment by ebebbington** [comment]
I just tested it and you are correct... iI swear that was the property value when using `Object.keys()`! I've gone crazy :P

**Comment by crookse** [comment]
I added a `console/build_docs` script. Run that script and the `api_reference.json` file will be written to your `/path/to/deno-drash` directory. You can take that file and make a PR to deno-drash-docs.

**Comment by ebebbington** [comment]
Alright sure thing, so it'll end up being two PR's? (Cookie feature for `deno-drash` and docs update for `deno-drash-docs`)

**Comment by crookse** [comment]
It doesn't have to be. I can pull your cookies PR down locally, build the `api_reference.json` file from it, and deploy the results to the staging env. It's up to you how you want to approach it.

**Comment by ebebbington** [comment]
Ah ok I just checked, i'm getting confused sorry! I'll run the build script (and check it) and then make the PR later when I've got the time

**Comment by crookse** [comment]
Sounds great! Also, I think it'll be easier to talk in the gitter chat. I'm pretty active on gitter, so I'll be able to see and respond to your messages about Drash almost immediately.

https://gitter.im/drashspace/community (if you prefer)

**Comment by ebebbington** [comment]
Yes that would be much better to be fair, means i'm not cluttering issues

**Comment by saragee3** [comment]
Can this be closed now? @crookse @ebebbington

**Comment by ebebbington** [comment]
I've yet to update the docs in deno-drash-docs, working on getting an env setup to run the repo
