### ISSUE TITLE
Deno v0.36.0 and v0.37.0 support

### ISSUE THREAD

**Issue by eliassjogreen** [drashland/deno-drash#155]
## Summary

This is probably something already being worked on and i am probably just nagging but deno v0.36.0 and v0.37.0 support would be nice to have. Currently when i tried to upgrade the dependencies failing in the old version it failed at the following test: `missing CSRF token` and errored at the following test `wrong CSRF token` (#138). When running the example everything seemed to work fine otherwise.

**Comment by crookse** [comment]
@eliassjogreen,

It’s done!

**Comment by crookse** [comment]
The tests have been problematic since deno v0.34.0. Not sure why. I did make another ticket though to address those issues. Everything does look fine otherwise like you said.
