### ISSUE TITLE
Tests leaking async ops

### ISSUE THREAD

**Issue by crookse** [drashland/deno-drash#157]
Check the following:

`server_test.ts`
`middleware_test.ts`
`cookie_resource.ts`

**Comment by ebebbington** [comment]
Wanna check on the server and middle ware test file:

* Has the issue been resolved in the server test? I don't see any cases commented out and run them fine

* Also was the middleware test leaking async ops for the following lines (that are commented out): `tests/unit/http/middleware_test.ts:10-32`?

Believed to have fixed the cookie one, but oddly if that test in the cookie test was uncommented and failed, then the files reosurce ended leaking async ops :S Not a problem now, just wierd...

**Comment by crookse** [comment]
Yea I know... it is weird. I couldn't reproduce the issue, so maybe it's been resolved ?

**Comment by ebebbington** [comment]
I guess so? i neither you or me can

Ok is it cool if i uncomment that specific test in middleware and the cookie one too? then i can push it up as a fix
