### ISSUE TITLE
static_paths default or extend

### ISSUE THREAD

**Issue by pgg** [drashland/deno-drash#159]
## Summary
provide a default path capability for a bare static_paths request or way to extend the resource
What: Explain ...
if a bare request is done for a configured static path ie '/app' with a default ie 'index.html' it should serve the default ie /app/index.html 
Why: Explain ...
serve app with a pretty url http://domain.tld/app
## Acceptance Criteria

- explained above

## Example Pseudo Code (for implementation)
at the moment static paths can't be configured like other resources, but it should behave like this and also still serve the other static resources
```typescript
export class StaticResource extends Drash.Http.Resource {
  static paths = ['/app'];
  public GET() {
    try {
      const raw = Deno.readFileSync(`./app/index.html`);
      this.response.body = new TextDecoder().decode(raw);
      return this.response;
    } catch (error) {
      throw new Drash.Exceptions.HttpException(400, 'index error');
    }
  }
}
```

**Comment by crookse** [comment]
@pgg ,

See https://drash.land/docs/#/tutorials/misc/pretty-links
