### ISSUE TITLE
Abstract the Logic that Gets View Contents

### ISSUE THREAD

**Issue by ebebbington** [drashland/deno-drash#161]
## Summary

What: Abstract the logic that reads a view file and decodes it into a serpate method that takes a view name.

Why: Simplifies the code the user has to write, resulting i less boilerplate the user has to add. Will result in a single line of code the user has to write, instead of creating a decoder and writing that logic themselves

## Acceptance Criteria

* Logic required to return a view file is handled within a new custom method Drash implements

* User should be able to get a views contents with: `this.response.render('/users/add.html', { data })

* Update Documentation

## Example Pseudo Code (for implementation)

** Server constructor would need to check if there's a `views_path` if `views_renderer` exists **

```typescript
constructor(...) {
  if (configs.views_renderer && !configs.views_path) {
    throw an error
  }
}
```

** Server configs would need updating:**

```typescript
interface ServerConfigs {
  ...
  views_path?: string,
  views_renderer?: any
```

**The views path and renderer would need to be passed in to the instantiation of the response class in `Drash.Http.Server.handleHttpRequest()` and anywhere else a `response` object is created in the `server` object**

```typescript
// server.ts
new Drash.Http.Response(request, {
  views_renderer: this.configs.views_renderer,
  views_path: this.configs.views_path
});
```

**Response class would need to add some extra configuration and a new method**

```typescript
Response {
  constructor(request: any, options: any = {}) {
    this.request = request;
    this.headers = new Headers();
    if (options.views_renderer) {
      this.renderer = options.views_renderer;
      this.views_path = options.views_path; // if there's a views renderer, then there must be a views_path
    };
    this.headers.set("Content-Type", request.response_content_type);
  }
  public render(...args) {
    args[0] = this.views_path += args[1];
    return this.renderer(...args);
  }
}
```

## Example Pseudo Code (for user)

```typescript
// app.ts
import { render } from "dejs/mod.ts"; // if the user wants to use dejs

class MyResource extends Drash.Http.Resource {
  public GET() {
    // Get dejs view with dynamic data
    this.response.body = this.response.render("users/add.ejs", {my: "data", goes: "here"});
    // get dejs view with no dynamic data
    this.response.body = this.response.render("/users/add.dejs")
    // get html view with no dynamic data
    this.response.body = this.response.render("/users/add.html")
    // get html view with dynamic data
    this.response.body = this.response.render("/users/add.html", {my: "data", goes: "here"})
    return this.response;
  }
}

const server = ({
  ...
  views_path: "path/to/views", // can be omitted if not rendering views
  views_renderer: render// can be omitted if not rendering views
})

**Comment by crookse** [comment]
I feel like `this.requireView` has unnecessary code. One of the reasons why Deno's import statements requires a `.ts` extension is because it doesn't take much effort to be more explicit. Granted, your code is just pseudocode, but it's something we have to think about. Saying `users/add.html` (I think) is better than `users.add` because you know the extension and you know it's in a subdirectory as opposed to what looks like a `user` object.

```
this.response.body = this.response.view("/users/add.html", { name: "Edward", alias: "ebebbington" });

public view(file: string, data: any = {}): string {
  let template: string = Deno.readFileSync(this.server.configs.views_path + file);
  if (!template) {
    return "View does not exist";
  }
  template = {template engine logic}
  return template;
}
```

**Comment by ebebbington** [comment]
Updated the issue following your comment

**Comment by crookse** [comment]
Currently awaiting https://github.com/syumai/dejs/issues/40
