### ISSUE TITLE
Namespace for Loggers

### ISSUE THREAD

**Issue by crookse** [drashland/deno-drash#18]
Summary
---

What: Drash should have a `Loggers` namespace where all loggers can be stored for global use.

Why: Importing the Drash namespace in each file instead of having multiple import lines cleans up the file and creates one way to grab the loggers.

Acceptance Criteria
---
- [x]  A logger object should be accessible via `Drash.Loggers.MyCoolLogger.info("Hello!");`
- [x]   A logger object can be added to the `Drash.Loggers` namespace. _This requires renaming the current `Drash.Loggers` namespace._
- [x]   Names of logger objects in the `Drash.Loggers` namespace must be unique. An error should be thrown if a logger is added with a duplicate name.
- [x]  Tests
    - [x]  Tests will need to be written for the `addLogger` functionality.
    - [x]  Tests will need to be updated when the current `Drash.Loggers` namespace is renamed.
- [x]  Documentation
    - [x]  Update all pages under the Tutorials > Logging section.
    - [x]  Update the Tutorials (Creating An App) > Hello World > Part 4 of 4: Logging page
    - [x]  _If you rename the `src/loggers` directory, then the directory list in `docs/docs.ts` will need to be updated. There is a `compileApiReferencePageData()` function that generates the API Reference page's JSON--using a directory list (a list of directories that it reads through) to find data and store it as JSON._ 

Example Pseudo Code (for implementation)
---

```typescript
// File: mod.ts

Drash {
  ...
  Loggers: {},
  ...
  addLogger(name: string, logger: any) {
    this.Loggers[name] = logger;
  }
}
```

```typescript
// File: app.ts (where the logger object is defined and added to Drash.Loggers)

import Drash from "https://deno.land/x/drash/mod.ts";

let myLogger = new Drash.Loggers.FileLogger({
  enabled: true,
  level: "debug"
});

Drash.addLogger("MyLogger", myLogger);
```

```typescript
// File: some_file.ts (where the logger object is used--just by importing Drash and referencing Drash.Loggers.MyLogger)

import Drash from "https://deno.land/x/drash/mod.ts";

// Access the MyLogger in the Loggers namespace and write an info log message
Drash.Loggers.MyLogger.info("test");
```

**Comment by Lonniebiz** [comment]
One nice thing about namespaces, versus imports, is the consistent "path length" that namespaces offer. Since `import` only accepts URLs and relative paths, the relative paths grow longer as code file are placed deeper in the directory hierarchy.

For example, if your app goes 4 folders deep, you'd end up with an import that looks like this:
`import { logger } from '../../../../Logs/logFile1.js';`

On the other hand, namespaces are in the global space and cannot benefit from tree-shaking and namespace could get more bloated than what's needed. Personally, I endure imports: the code page may look a little bloated, but the runtime is lean.

**Comment by crookse** [comment]
@Lonniebiz,

You make a good point. I didn't think about tree shaking when I wrote this feature. I don't think adding the logic to support this would hurt though. Adding the logic would just add the convenience of using namspaced loggers (if anyone would want to go that route).

**Comment by crookse** [comment]
@saragee3,

i updated the acceptance criteria.
