### ISSUE TITLE
asynchronous middleware

### ISSUE THREAD

**Issue by dylanblokhuis** [drashland/deno-drash#188]
**Describe the bug**
Whenever the run() method is asynchronous, the exceptions are uncaught.

**To Reproduce**

1. Create a middleware class
2. Add the async keyword to the run() method.
3. Try out the middleware and cause an exception with HttpException or HttpMiddlewareException
4. See error in console

It could be that asynchronous middleware are not a good pattern, if thats the case you can close this issue.

**Comment by crookse** [comment]
We're actually in the middle of refactoring our middleware. I will let the developers working on the refactor know that `async-await` should be accounted for. Thanks @dylanblokhuis !

**Comment by crookse** [comment]
Hey @Guergeiro / @ebebbington,

We need to make sure `async-await` works with the new middleware stuff.

**Comment by dylanblokhuis** [comment]
Thanks for the response, I've been having a blast using drash. Keep it up!

**Comment by crookse** [comment]
> Thanks for the response, I've been having a blast using drash. Keep it up!

You're welcome! And thank you! Very much appreciated :)
