### ISSUE TITLE
Support for HTTP Method OPTIONS

### ISSUE THREAD

**Issue by alexjamesmalcolm** [drashland/deno-drash#194]
## Summary

What: It appears that Drash doesn't handle HTTP requests of method `OPTION` and also does not allow for a way to override them.

Why: This is important regarding CORS. My scenario is my frontend is hosted on a different port than my backend so I have to deal with CORS locally but not in production. Regardless, for those dealing with CORS, since `OPTION` is not implemented a Response of `405`. Since this is not `2xx` the browser fails the CORS preflight check.

## Acceptance Criteria
Add an `OPTION` method to the `Drash.Http.Resource` class to be overridden by users. It'd also be nice if a default method was generated since most frameworks also handle this for the developer.

## Example Pseudo Code (for implementation)
```typescript
export class LobbyResource extends Drash.Http.Resource {
  static paths = ["/lobby", "/lobby/", "/lobby/:lobby_id", "/lobby/:lobby_id/"];
  public OPTION() {
    console.log("Received option request");
    this.response.status_code = 200;
    this.response.headers.append("Allow", "GET,POST,PUT,DELETE,OPTION");
    return this.response;
  }
}
```

**Comment by alexjamesmalcolm** [comment]
🤦 Wow, simple problem of thinking the HTTP method was called `OPTION` and not `OPTIONS`. I still think there's merit in creating a default implementation of a response to `OPTIONS` requests with a list of `Allow`ed methods.

**Comment by crookse** [comment]
Are you saying the `Response` class should implement a way to set the status code to `200` and the `Allow` header to `GET,POST,PUT,DELETE,OPTION` for `OPTIONS` requests?

**Comment by alexjamesmalcolm** [comment]
I'd like to have a default implementation of an `OPTIONS` request handler. The user (developer) could always override this for their own purposes.

So this is what my `OPTIONS` method looks like:
```typescript
public OPTIONS() {
  this.response.status_code = 200;
  this.response.headers.append("Allow", "*");
  return this.response;
}
```
If you want to see the above code in context here's a [link](https://github.com/alexjamesmalcolm/bid-euchre-http-game-engine/blob/master/resources/GameResource.ts).

That's alright in a pinch but it's too broad in the HTTP methods it allows, it should only be the methods defined in the class. We could do this dynamically and for the user by having a default implementation of `OPTIONS` that looks something like this:
```typescript
public OPTIONS() {
  const allHttpMethods: string[] = [
    "GET",
    "HEAD",
    "POST",
    "PUT",
    "DELETE",
    "CONNECT",
    "OPTIONS",
    "TRACE",
    "PATCH",
  ];
  this.response.status_code = 200;
  this.response.headers.append(
    "Allow",
    allHttpMethods.filter(
      (method: string) => typeof this[method] === "function"
    )
  );
  return this.response;
}
```
There's some problems with this code, like that typescript doesn't like the `(method: string) => typeof this[method] !== "function"` part.

**Comment by Guergeiro** [comment]
I'm not sure if providing a default implementation of `OPTIONS` is that important. From my point of view the developer should have full control over this, specially because of *CORS*. Imagine providing a vulnerability because we added default implementation of `OPTIONS`.

Either way, if @crookse thinks it's good, just assign me to this issue.

**Comment by player-4** [comment]
@alexjamesmalcolm,

what you could do is extend `Drash.Http.Resource` and use your extended class instead. here's an example.

```typescript
import Drash from ...

class MyBaseResource extends Drash.Http.Resource {
  public OPTIONS() {
    const allHttpMethods: string[] = [
      "GET",
      "HEAD",
      "POST",
      "PUT",
      "DELETE",
      "CONNECT",
      "OPTIONS",
      "TRACE",
      "PATCH",
    ];
    this.response.status_code = 200;
    this.response.headers.append(
      "Allow",
      allHttpMethods.filter(
        (method: string) => typeof this[method] === "function"
      )
    );
    return this.response;
  }
}

class HomeResource extends MyBaseResource {
  static paths = ["/"]
}

const server = new Drash.Http.Server({ ... });

server.run({ ... });

```

if you dont want to keep importing your `MyBaseResource` class in every resource file that you create, then you can replace `Drash.Http.Resource` with your class. here's an example.

```typescript
import Drash from ...

class MyBaseResource extends Drash.Http.Resource {
  public OPTIONS() {
    const allHttpMethods: string[] = [
      "GET",
      "HEAD",
      "POST",
      "PUT",
      "DELETE",
      "CONNECT",
      "OPTIONS",
      "TRACE",
      "PATCH",
    ];
    this.response.status_code = 200;
    this.response.headers.append(
      "Allow",
      allHttpMethods.filter(
        (method: string) => typeof this[method] === "function"
      )
    );
    return this.response;
  }
}

Drash.Http.Resource = MyBaseResource;

class HomeResource extends Drash.Http.Resource {
  static paths = ["/"]
}

const server = new Drash.Http.Server({ ... });

server.run({ ... });
```

**Comment by Guergeiro** [comment]
Agreed @player-4

**Comment by crookse** [comment]
@alexjamesmalcolm, does @player-4 address your issue? Please let us know. Thanks!

**Comment by alexjamesmalcolm** [comment]
@crookse Yes it should, I'll have to come up with a way to get `(method: string) => typeof this[method] === "function"` to work but I should be good. Feel free to close or leave open this ticket depending on if you want to go in that direction.

**Comment by Guergeiro** [comment]
Hello @alexjamesmalcolm. You can't use the `this[method]` since `this` is referencing a Resource and there are no methods available there (unless you access prototype).

Here's what you should do.

```typescript
class MyBaseResource extends Drash.Http.Resource {
  public OPTIONS() {
    const allHttpMethods: string[] = [
      "GET",
      "POST",
      "PUT",
      "DELETE"
    ];
    this.response.headers.set("Allow", allHttpMethods.join()); // Use this
    this.response.headers.set("Access-Control-Allow-Methods", allHttpMethods.join()); // or this
    this.response.status_code = 204;
    return this.response;
  }
}
class HomeResource extends MyBaseResource {
  static paths = ["/"];
  public GET() {
    this.response.body = "HELO";
    return this.response;
  }
}
```

This way, when I client ask for the `OPTIONS` in **any** of your resources, the server replies with the allowed methods. If you want to override the *MyBaseResource* implementation of `OPTIONS`, just create the method `OPTIONS` for that specific resource.

I followed the the recommendations of MDN. You can check about my source [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS).
