### ISSUE TITLE
Cannot resolve extension with mediaType "Json"

### ISSUE THREAD

**Issue by mrtycjan** [drashland/deno-drash#209]
Issue type:

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

> - drash 0.42.0
> - deno 1.0.0-rc1
> - v8 8.2.308
> - typescript 3.8.3

main.ts
```
import { Drash } from "https://deno.land/x/drash@v0.42.0/mod.ts";

class HomeResource extends Drash.Http.Resource {
  static paths = ["/"];
  public GET() {
    this.response.body = "Hello World!";
    return this.response;
  }
}

const server = new Drash.Http.Server({
  response_output: "text/html",
  resources: [HomeResource]
});

server.run({
  hostname: "localhost",
  port: 1447
});

```
when i run 

`deno  run --allow-net  main.ts`

result in console is

```
Compile file:///home/tsobel/projects/deno/main.ts
error: Uncaught TypeError: Cannot resolve extension for "https://deno.land/x/drash@v0.42.0/src/dictionaries/mime_db.json" with mediaType "Json".
    at getExtension ($deno$/compiler/sourcefile.ts:42:13)
    at new SourceFile ($deno$/compiler/sourcefile.ts:70:22)
    at processImports ($deno$/compiler/imports.ts:122:45)
    at async processImports ($deno$/compiler/imports.ts:125:7)
    at async Object.processImports ($deno$/compiler/imports.ts:125:7)
    at async compile (file:///home/runner/work/deno/deno/cli/js/compiler.ts:144:31)
    at async tsCompilerOnMessage (file:///home/runner/work/deno/deno/cli/js/compiler.ts:359:22)
    at async workerMessageRecvCallback ($deno$/runtime_worker.ts:73:9)
❯ 
```

**Comment by Guergeiro** [comment]
Hello @mrtycjan 

It seems you're using a version of Drash that is not compatible with Deno `v1.0.0rc1`.

Please either update Drash to `v1.0.0rc1` or downgrade your version of Deno.

I'll be waiting for your response.

**Comment by Guergeiro** [comment]
To update Drash you can just download the latest [release](https://github.com/drashland/deno-drash/releases). To downgrade Deno, please refer to their [install](https://github.com/denoland/deno_install) instructions.

**Comment by Guergeiro** [comment]
I'm going to close this issue by assuming that @mrtycjan was able to solve the problem.

**Comment by mrtycjan** [comment]
@Guergeiro thanks, works fine with newest deno version

**Comment by MedinaGitHub** [comment]
no funciona =( 
![image](https://user-images.githubusercontent.com/16387514/168456189-c205e63d-643f-4bb7-8bc7-2529529f04fd.png)

**Comment by crookse** [comment]
hi @MedinaGitHub , did you have a question?
