### ISSUE TITLE
More details on how to add resources

### ISSUE THREAD

**Issue by douglaschalegre** [drashland/deno-drash#221]
## Summary
Add multiple resources implementation on [Creating a resource](https://drash.land/docs/#/tutorials/resources/creating-a-resource)

I was just following the tutorial and had a trouble to findout how to add multiple resources to the server. 

## Example Pseudo Code (for implementation)
When on [Path Params](https://drash.land/docs/#/tutorials/resources/creating-a-resource#path-params) we're creating a totally diferrent resource, so i thought it should be a new resource and we would keep both, but took me a few time to find out how to actually add it to 
`const server = new Drash.Http.Server({
  resources: [HomeResource],
});`
On [Path Params](https://drash.land/docs/#/tutorials/resources/creating-a-resource#path-params) teach how to add multiple resources on `Drash.Http.Server()` changing it from this:
```typescript
import { Drash } from "https://deno.land/x/drash@v1.0.2/mod.ts";

import HomeResource from "./home_resource.ts";

const server = new Drash.Http.Server({
  resources: [HomeResource, UsersResource],
});

server.run({
  hostname: "localhost",
  port: 1447
});
```
to this:
```typescript
import { Drash } from "https://deno.land/x/drash@v1.0.2/mod.ts";

import HomeResource from "./home_resource.ts";
import UsersResource from "./users_resource.ts"

const server = new Drash.Http.Server({
  resources: [HomeResource],
});

server.run({
  hostname: "localhost",
  port: 1447
});
```

**Comment by douglaschalegre** [comment]
I dont know why but i cant add a doc label on this

**Comment by Guergeiro** [comment]
Hello @douglaschalegre, thanks for your input. We will look into it.

Do you have any other question that might not be straight forward via our docs?

**Comment by douglaschalegre** [comment]
Hi @Guergeiro , for now no, i dont have

**Comment by crookse** [comment]
Hi @douglaschalegre ,

We're currently having issues generating our docs, so we have to resolve that issue before regenerating our docs. Our docs use an unstable Deno API (walkSync) and it only works sometimes (I don't know what causes it to work), but I will regenerate the docs with updated and clearer information as soon as I can. Thank you for input though. Greatly appreciated!

**Comment by crookse** [comment]
Hey @douglaschalegre , I've rewritten the docs. https://drash.land/docs/#/tutorials/resources/creating-a-resource

It immediately tells you how to add multiple resources; and the examples only use the `HomeResource`, so it's easier to follow along. Let me know if this is a good rewrite. If not, I'd like your feedback and will rewrite again. Thanks!

**Comment by douglaschalegre** [comment]
Hi @crookse, the new docs it's awesome even better then i've sugested.

Thanks :)

**Comment by crookse** [comment]
@douglaschalegre,

Great! And thank you for your feedback! Please don't hesitate to let us know if other parts of our documentation needs more clarity.
