### ISSUE TITLE
Server crashed when an error occurred

### ISSUE THREAD

**Issue by haverzard** [drashland/deno-drash#223]
**Describe the bug**
An error that can occur inside handleHttpRequest method is not caught by the try-catch block in Server.run method.

**To Reproduce**
1. Update to latest Deno/Drash release.
2. Create simple server with a resource that can accept body data.
3. Send invalid json data (for example '.') to the resource.
4. An error will occur and the server will crash.

**Expected behavior**
The error is caught by the try-catch block.

**Suggested Solution(s)**
Moving the try-catch block inside an async function and await for handleHttpRequest to finish. This will keep the same behaviors and catch the error.

     (async () => {
          try {
            await this.handleHttpRequest(request);
          } catch (error) {
            this.handleHttpRequestError(request, this.httpErrorResponse(500));
          }
     })()

**Comment by Guergeiro** [comment]
Hello @haverzard 

Thanks for your feedback. We will look into it and come back to it as soon as possible.

**Comment by Guergeiro** [comment]
@haverzard could you paste a code of your example? That way I can specifically target it and also try to find similar behaviours.

**Comment by haverzard** [comment]
Here is the code example:

    import { Drash } from "https://deno.land/x/drash@v1.0.2/mod.ts";

    class HomeResource extends Drash.Http.Resource {
      static paths = ["/"];

      public async GET() {
        await new Promise(r => setTimeout(r, 10000));
        this.response.body = "Hello world!";
        return this.response;
      }

      public POST() {
        const param = this.request.getBodyParam("name");

        if (!param) {
          throw new Drash.Exceptions.HttpException(
              400,
              "This resource requires the `name` body param."
          );
        }

        this.response.body = `You passed in the following body param: ${param}`;

        return this.response;
      }
    }

    const server = new Drash.Http.Server({
      response_output: "application/json",
      resources: [HomeResource],
    });

    server.run({
      hostname: "localhost",
      port: 5000,
    });

I tried to send a GET request to HomeResource (`curl localhost:5000`) and while it was still waiting for a response, I sent a POST request to HomeResource with invalid json data (`curl localhost:5000 -H "Content-Type: application/json" -X POST "."`). The server crashed and both requests didn't receive any response.

I was expecting the POST request to receive an error response first and then after a few seconds, the GET request received its response.

**Comment by crookse** [comment]
@Guergeiro,

Check here: https://github.com/drashland/deno-drash/blob/master/src/services/http_request_service.ts#L507-L510

**Comment by crookse** [comment]
We're parsing JSON assuming the JSON is correct and getting this error:

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at HttpRequestService.parseBodyAsJson (file:///private/var/src/drashland/deno-drash/src/services/http_request_service.ts:511:19)
    at async HttpRequestService.parseBody (file:///private/var/src/drashland/deno-drash/src/services/http_request_service.ts:454:20)
    at async HttpRequestService.hydrate (file:///private/var/src/drashland/deno-drash/src/services/http_request_service.ts:334:52)
    at async Server.getRequest (file:///private/var/src/drashland/deno-drash/src/http/server.ts:203:15)
    at async Server.handleHttpRequest (file:///private/var/src/drashland/deno-drash/src/http/server.ts:233:15)
```

That blows up the application completely.

**Comment by crookse** [comment]
Hi @haverzard,

The issue is fixed and the fix is released. Use the following:

```
import { Drash } from "https://deno.land/x/drash@v1.0.3/mod.ts";
```
