### ISSUE TITLE
CI To Check for New Deno Versions

### ISSUE THREAD

**Issue by ebebbington** [drashland/deno-drash#228]
Placeholder issue until more information is gathered around this new feature

## Summary
As quoted by @Guergeiro:

> My vision would be to have a CI that checks for a Deno version every day. When a new version is found, it creates a new branch and opens a PR. Then we accept it or fix problems if it exists. That way we don't import it, it just stays in the CI.

What: Explain ...

Why: Explain ...

## Acceptance Criteria

- Add acceptance criteria as bulleted list

## Example Pseudo Code (for implementation)

```typescript
// Add example pseudo code for implementation
```

**Comment by ebebbington** [comment]
Anyone have knowledge on how the CI could achieve this? Or experience with this type of process in the CI

**Comment by Guergeiro** [comment]
I do 😄

**Comment by ebebbington** [comment]
This issue has you're name all over it then :D
