### ISSUE TITLE
Drash.HTTP.Server.getRequest() returns request without a body.

### ISSUE THREAD

**Issue by gabrielgrover** [drashland/deno-drash#246]
## Having an issue with Drash.HTTP.Server.getRequest()

What: When I call getRequest() and pass in a Request object I get back a Request without a body.  

Why: One of the dependencies in that method calls HttpRequestService.parseBody which, in turn, calls Deno.readAll(request.body).  The body in a Request object is a readable stream and not a Reader.  It therefore Deno.readAll(request.body) returns null.  

The reason why I am doing this is because I am trying to make a MockRequest object that I can pass to a class that extends Drash.Http.Resource in order to write some integration tests for an endpoint.  

## Acceptance Criteria

- Add acceptance criteria as bulleted list
  - Provided a different was to create a request object that I can pass in the constructor of a 
     Drash.Http.Resource or an actual type declaration for the request object.  

## Example Pseudo Code (for implementation)

```typescript
   const body = JSON.stringify({ hello: "world" });
   const req = new Request("hello.com", { method: "POST", body });
   const newReq = server.getRequest(req);
  
  newReq.getBodyParam("hello");

 -> undefined
```

**Comment by crookse** [comment]
This is just a guess, but I think what's happening here is you don't have the `"Content-Type": "application/json"` header set. What happens if you set that?

**Comment by crookse** [comment]
Also, is there a reason why you're using Request instead of ServerRequest?

**Comment by gabrielgrover** [comment]
@crookse No reason.  Where is ServerRequest defined?  Also when I add the headers I get 

SyntaxError: Unexpected end of JSON input

The error is happening in this method 

```
public async parseBodyAsJson(request: any): Promise<object> {
    const data = decoder.decode(await Deno.readAll(request.body));
    return JSON.parse(data);
  }
```

It is because data is an empty string when it is being parsed.  When I log request.body it is a ReadableStream.  I believe Deno.readAll takes a Reader type.

**Comment by crookse** [comment]
I think what's happening is `request.body` is not encoded. I think there are more issues than that though because you're using `Request` instead of `ServerRequest`. Try the following test. It has a `mockRequest` function that you may be interested in.

```typescript
import { Drash } from "https://deno.land/x/drash@v1.0.5/mod.ts";
import { BufReader } from "https://deno.land/std@v0.56.0/io/bufio.ts";
import { ServerRequest } from "https://deno.land/std@v0.56.0/http/server.ts";
import { assertEquals } from "https://deno.land/std@v0.56.0/testing/asserts.ts";

const mockRequest = function(url: string, method: string, options?: any) {
  let request = new ServerRequest();
  request.url = url;
  request.headers = new Headers();
  if (options) {
    if (options.headers) {
      for (let key in options.headers) {
        request.headers.set(key, options.headers[key]);
      }
    }
    if (options.body) {
      request.headers.set("Content-Length", options.body.length.toString());
      const encodedBody = new TextEncoder().encode(options.body);
      const reader = new Deno.Buffer(encodedBody as ArrayBuffer);
      request.r = new BufReader(reader);
    }
  }
  return request;
}

Deno.test("getRequest()", async () => {
  const server = new Drash.Http.Server({ resources: [HomeResource] });
  const request = mockRequest("/", "get", {
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({hello: "world"})
  });
  const newRequest = await server.getRequest(request);
  assertEquals("world", newRequest.getBodyParam("hello"));
});

////////////////////////////////////////////////////////////////////////////////
// DATA ////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

class HomeResource extends Drash.Http.Resource {
  static paths = ["/"];
  public async GET() {
    this.response.body = "Hello world!";
    return this.response;
  }
}

```

**Comment by gabrielgrover** [comment]
That did the trick.  Thanks a bunch @crookse!  Closing this out!

**Comment by crookse** [comment]
np @gabrielgrover !
