### ISSUE TITLE
chore: clean up branches; make v1.x branch

### ISSUE THREAD

**Issue by crookse** [drashland/deno-drash#259]
## Summary

What: Now that Deno has released v1.x, we should make a branch to reflect our v1.x.

Why: For documentation purposes, it'll be easier to deploy containers set to a certain branch. For example:

```
URI https://drash.land/docs/v1.x -> container with branch release/v1.x checked out
URI https://drash.land/docs/v2.x -> container with branch release/v2.x checked out
URI https://drash.land/docs/v3.x -> container with branch release/v3.x checked out
```

For development purposes, it'll be easier to support old versions.

**Comment by ebebbington** [comment]
Makes sense to me, i think this was in effect (well similar) quite a while back too eg

```
release/v0.36.0
release/v0.35.0
```
I've cleaned all my unused branches, would we just branch off of master to make `v1.0.7` (for example) when a theres a new release, then keep PR's commiting to master as usual?

**Comment by ebebbington** [comment]
So a v1.x branch was made from the v1.0.7 release - when would we merge master into it? On each release for 1.x?

**Comment by Guergeiro** [comment]
Yes. We can use the same logic of the bumper workflow. We create a PR from master->v1.x.

**Comment by crookse** [comment]
done
