### ISSUE TITLE
create_app.ts - add --with-react flag

### ISSUE THREAD

**Issue by crookse** [drashland/deno-drash#260]
## Summary

What: Add `--with-react` optional flag when `--web-app` is used.

Why: Currently, we can call the `create_app.ts` script with `--web-app --with-vue`. It would be nice to have `--web-app --with-react`. The `--with-vue` option creates all necessary directories and files needed to run a Drash server with a Vue front-end. Seee how `--web-app --with-vue` works to figure out how `--web-app --with-react` should work. They should be pretty similar.

## Acceptance Criteria

- [x] `create_app.ts` can run with `--web-app --with-react`
- [x] Documentation (https://github.com/drashland/website/issues/212)

## Example Pseudo Code (for implementation)

The following would be the command to implement.

```typescript
deno run --allow-run --allow-read --allow-write /path/to/create_app.ts --web-app --with-react
```

**Comment by ebebbington** [comment]
only just realised i was assigned... may as well work on it now
