### ISSUE TITLE
Make `deno lint` Pass

### ISSUE THREAD

**Issue by ebebbington** [drashland/deno-drash#264]
## Summary

What: If you run `deno lint`, we will most likely have a whole bunch of errors. This issue to fix these errors by correctly formatting code, and abiding by Deno's standards 

Why: It would be good to make sure the code follows either: Deno's best practices, coding standards, or general best practices. It's a Deno project so it makes sense to utilise their tools on making the code Deno-like

## Acceptance Criteria

- `deno lint` is added to the `master.yml` CI, as a new block (similar to how we use `deno fmt --check` on some repositories)
- `deno lint` produces no errors

## Resources

[Deno Lint Documentation](https://github.com/denoland/deno_lint)

**Comment by Guergeiro** [comment]
For new comers, we will only ship lint as soon as the `--unstable` flag is removed. But trying to make it work now might be a good idea since the rules will probably not change that much.
