### ISSUE TITLE
linting - remove any in ParsedRequestBody interface

### ISSUE THREAD

**Issue by crookse** [drashland/deno-drash#277]
What: Improve `ParsedRequestBody` interface by removing `any` type. See screenshot below for context about this issue.

<img width="823" alt="Screen Shot 2020-06-28 at 11 36 43" src="https://user-images.githubusercontent.com/12766301/85951859-dff3f800-b933-11ea-9ad5-ff94b6eee9f2.png">

Why: Improve the quality of the codebase.

Acceptance Criteria:

If this issue is possible to overcome:

- [ ] remove `any`
- [ ] tests pass

**Comment by ebebbington** [comment]
Oh I know this! Bagsies!
