### ISSUE TITLE
Move resource level middleware to static props

### ISSUE THREAD

**Issue by gabrielgrover** [drashland/deno-drash#279]
## Summary

What: Right now resource level middleware is done through decorators.  It would be cool if we could do this through a static prop or method we define that follows a contract of some kind.

Why: Since resources are instantiated by Drash, in order for me to do dependency injection I do the following.  

``` typescript
export const createAccountResource = (repo: AccountServiceRepo) =>
  class AccountResource extends Drash.Http.Resource {
    static paths = [
      "/account",
    ];

    public async GET() {
      const isValidToken = await this.checkToken();

      if (!isValidToken) {
        return Promise.reject(new Drash.Exceptions.HttpException(400, "Invalid token."))
      }

      const { email } = this.headerTokenPayload;
      const { name } = await repo.findBasicAccount(email);

      this.response.body = {
        email,
        name
      };

      return this.response;
    }

    public async POST() {
      const { email, password, name } = this.getBody(
        ["email", "password", "name"],
      );
      const token = createBasicAuthToken(email);

      const [err, data] = await to(repo.createBasicAccount({ name, email, password }));

      if (err) {
        return Promise.reject(new Drash.Exceptions.HttpException(400, err.message));
      }

      this.response.body = { ...data, token };

      return this.response;
    }

    private get headerTokenPayload(): Record<string, any> {
      const token = this.headerToken;

      return getPayload(token);
    }

    private get headerToken(): string {
      return getBearerToken(this.request);
    }

    private checkToken(): Promise<boolean> {
      const token = this.headerToken;
      return checkJWT(token);
    }

    private getBody(params: string[]): Record<string, any> {
      return params.reduce((result, param): Record<string, any> => {
        return {
          ...result,
          [param]: this.request.getBodyParam(param),
        };
      }, {});
    }
  };
```

Since decorators do not work on functions or inside them I am unable to use resource level middleware. 

## Acceptance Criteria

Being able to define resource level middleware using class static props or methods.

## Example Pseudo Code (for implementation)

I am imagining something like this

```typescript
class SomeResource extends Drash.Http.Resource {
  beforePost(req, res) { }

  afterPost(req, res) { }

  beforeGet(req, res) { }

  afterGet(req, res) { }
}
```

or this

```typescript
class SomeResource extends Drash.Http.Resource {
  static middlewares = [
    { method: "method_name", func: (req, res) => {...}, before: true }, 
    { method: "other_method_name", func: (req, res) => {...}, after: true }, 
  ];
}
```

**Comment by Guergeiro** [comment]
Hello @gabrielgrover, I'm finding trouble understanding your situation (maybe you could provide a snippet of what you want inject and how it would work)... Nevertheless, I can understand the use case behind defining a class middleware as a static attributes. I will talk with the dev team to check about the viability of this feature.

**Comment by gabrielgrover** [comment]
@Guergeiro Thanks for the quick response! The first code snippet shows what I am trying to inject.  It is subtle, but you can see that I am exporting a function that takes in an object that is an AccountServiceRepo (an interface that I have defined).  This function then returns a class.  The methods of that class can access the object passed into the function via a closure.  I can then pass in whatever I want for the repo like so 

```typescript
const AccountResource = createAccountResource(/*Some object that satisfies the AccountServiceRepo interface*/);

accountResource = new AccountResource(req, res);
```

**Comment by crookse** [comment]
Hey @gabrielgrover, I'm still have trouble trying to figure why you need to inject the dependency the way you're doing it. I'm wondering if this would be a viable solution for you:

```typescript
// File: app.ts

import { Drash } from "../mod.ts";
import AccountResource from "account_resource.ts";

const server = new Drash.Http.Server({
  logger: new Drash.CoreLoggers.ConsoleLogger({
    enabled: true,
    level: "debug",
  }),
  resources: [AccountResource],
});

// Instantiate new repo service and export it so that it can be used in
// resources that depend on it
import AccountServiceRepo from "account_service_repo.ts";
export const repo = new AccountServiceRepo();

```

```typescript
// File account_resource.ts

import { repo } from "app.ts";

class AccountResource {
  public GET() {
    repo.doSomething();
  }
}

```

If not, then I would recommend that you create an extension of the `Drash.Http.Server` class. You can extend it and override the `handleHttpRequest()` method. In that method is where the resources are constructed. You can copy and paste the default logic and change the logic surrounding resource construction to fit your needs.

Let me know if this is something that would solve your issue(s). If not, then I guess me and the dev team can get back together and think of a solution surrounding dependency injection for you.

**Comment by gabrielgrover** [comment]
@crookse Sorry for the confusion. I don't need a dependency injection solution from you guys per se.  I was looking more for a way to define resource level middleware on the resource itself via methods.  Or a way to define resource level middleware without using decorators.

**Comment by Guergeiro** [comment]
Hello again @gabrielgrover. This topic generated a lot of discussion internally.

**Short story:** We will not provide a way of defining middewares to resources using static parameters.

**Long story:** 
Decorating the class itself allows us to not care about the logic of associating a middleware to the class/method. That logic is handled by the TypeScript Compiler. We only make sure that the functions are run in the correct order and provide a signature to implement them correctly.
That being said, I understand why you wouldn't want to use TypeScript decorators. The quick solution to this is indeed providing middleware as static attributes and having logic behind in Drash to account for this. The problem with this comes down to performance. In earlier iterations of Drash, middleware was not declared via TypeScript decorators, but this added extra logic to our resource resolver, doing unnecessary comparisons to check for middlewares, resulting in performance issues (still really good performance). We hated this approach and moved from it arriving at the point we are today.
As far as what we want in the future is most likely to drop TypeScript decorators (especially since they are behind an experimental flag) and implement a Decorator Design Pattern that makes middleware in resources easy to implement. We just quite haven't figure out how to do it yet...

If you really do not want use TypeScript decorators, I can only think of one solution.
```typescript
function someMiddleware(req: Drash.Http.Request, res: Drash.Http.Response) {
  // Do stuff
}

class SomeResource extends Drash.Http.Resource {
  public GET() {
    // Execute middleware before
    someMiddleware(this.request, this.response);
    // Do method logic
    this.response.body = "hey";
    // Execute middleware after
    someMiddleware(this.request, this.response);
    return this.response;
  }
}
```
I know it's not perfect, but it's currently what we can provide.

**Comment by Guergeiro** [comment]
I will now close this issue. Will come back to it if needed.
