### ISSUE TITLE
Remove the any type from middleware logic

### ISSUE THREAD

**Issue by crookse** [drashland/deno-drash#283]
What: Remove `any` from middleware logic. Use types and interfaces.

Why: Improve the quality of the codebase.

Acceptance Criteria:

If this issue is possible to overcome:

- [ ] remove `any`
- [ ] tests pass

**Comment by ebebbington** [comment]
Oh wait, doesn’t the server middleware have the same “type”?

**Comment by crookse** [comment]
looks to be the case

**Comment by ebebbington** [comment]
Alright, well FYI for anyone who works on this issue (including me), the `server_middleware.ts` interface can be used - would just need to rename the file, interface and references to make it usable by both server and resource middleware eg naming it just “IMiddleware”

**Comment by Guergeiro** [comment]
They do have the same type. The only difference is that in the implementation of the Decorators, I used `any` because the factory associated with it (TypeScript factory) is weird.

**Comment by ebebbington** [comment]
Guessing there will be some weird oddities... 😰

**Comment by Guergeiro** [comment]
Essentially the factory associated with [this](https://github.com/drashland/deno-drash/blob/master/src/http/middleware.ts) is the weird stuff. Make it work in class level and method level is funky.

**Comment by ebebbington** [comment]
I've tried my hand a second time and can't not add proper strict types... D:

**Comment by ebebbington** [comment]
Closing as master (v2) no longer contains this
