### ISSUE TITLE
Video Tutorial - Create App Script

### ISSUE THREAD

**Issue by ebebbington** [drashland/deno-drash#309]
## Summary

What: Video tutorial (acts of visual documentation) for how to use Create App in Drash to create a Drash skeleton app, how it works, how to use them etc - acting as the documentation but in video form. Though it's open to whoever takes on this issue how they'd like to do the video and what content it will have.

Why: Supports visual learners, and thus creates another platform for people to understand on using Drash to create a skeleton - further enforcing "documentation driven"

## Information

* OBS can be used as the software to screenshare and video recording

* Includes the drashland introduction

* Includes the drash logo with the greenish background as the thumbnail

* Video can be added to a "Drash" playlist (can also be created if it doesn't exist)

* Make it chill :)

**Comment by ebebbington** [comment]
on hold as this will be moved under the cli

**Comment by ramonmedeiros** [comment]
I'm writing a small REST API with Drash and mongodb. I would like to implement an example using most used HTTP methods (GET, POST, PUT and DELETE). Right now I'm having a hard time with POST, related to how I parse the body as json.

I would like to make this video as soon I finish my sample application. How I can get more docs?

**Comment by ebebbington** [comment]
Hey @ramonmedeiros, don’t worry about making the video yourself :) I’ll do it, and as you’ve mentioned it I can make it tonight or tomorrow, and I’ll ping you when it’s done

For full documentation, you can go to https://drash.land/dmm

If you do have any questions or any information that you don’t have to do what you need to do with your Drash application, let us know :) we’ll gladly add more docs to make sure people have 100% certainty when using any drashland related modules

**Comment by ebebbington** [comment]
Sorry wrong link! Try https://drash.land/drash 

Note that Drash v1.3 will be put on Friday so something’s will be fixed and added and the docs will be updated too

**Comment by crookse** [comment]
hi @ramonmedeiros,

sorry for the confusion. these video tutorials are meant for the Drash Land org members. there's a process that videos must go through to end up on our YouTube and that process is defined in a private area that only Drash Land org members have access to.

i'm glad you're interested in making a video though. please feel free to make one and let us know about it. we'll be more than happy to showcase it in the Drash Land Discord channel :)

**Comment by crookse** [comment]
closing - moving this to the private task area
