### ISSUE TITLE
release.yml - automate tweeting new releases

### ISSUE THREAD

**Issue by crookse** [drashland/deno-drash#312]
## Summary

What: Add tweeting new releases to the release.yml file

Why: Currently, tweeting new releases is done manually. It'd be nice to have this automated on release events.

**Comment by MVEMCJSUNPE** [comment]
We can use [twitter-together](https://github.com/gr2m/twitter-together) for this.

**Comment by ebebbington** [comment]
@MVEMCJSUNPE nice! i think we'll look into this?
