### ISSUE TITLE
release.yml - make PR to branch v1.x on release

### ISSUE THREAD

**Issue by crookse** [drashland/deno-drash#320]
## Summary

What: Our `import` statements now target the `v1.x` branch. It'd be nice to have the `release.yml` file automatically make a PR of the latest code going into the `v1.x` branch.

Why: Automation is good.

**Comment by ebebbington** [comment]
Are we still having a v1.x branch with the new deno registry not allowing branches?

**Comment by crookse** [comment]
@ebebbington, nope. closing.
