### ISSUE TITLE
Introduce node_raw and fastify benchmarks for realistic comparisons with drash

### ISSUE THREAD

**Issue by trivikr** [drashland/deno-drash#322]
## Summary

- Deno (latest as issue creation is v1.2.0) http server serves around 25-40% less req/sec than that of Node.js (latest as issue creation is v14.5.0) as explained in https://github.com/denoland/deno/issues/6722
- Although Express is widely popular, it's amongst the slowest Web frameworks in Node.js
Fastify benchmarks https://www.fastify.io/benchmarks/
- Drash needs to add node_raw and fastify to its benchmarks to have realistic comparisons visible to it's users

## Acceptance Criteria

- node_raw and fastify benchmarks are added in drash benchmarks

## Example Pseudo Code (for implementation)

* Code for node_raw can be picked from Deno benchmarks: https://github.com/denoland/deno/blob/bfab4ed0dfa5e2034005133a257201c934bc3a80/tools/node_http.js
* Code for fastify can be picked from Fastro benchmarks: https://github.com/fastrodev/fastro/blob/dbb46e8e6913d1bfcb3468640d80c6600cc29331/benchmarks/fastify.js

**Comment by trivikr** [comment]
This suggestion came up from Reddit discussion https://www.reddit.com/r/Deno/comments/hrq37v/deno_http_server_serves_around_2540_less_reqsec/fy698bn/

**Comment by crookse** [comment]
Hey @trivikr, check out https://github.com/drashland/benchmarks
