### ISSUE TITLE
[Question] Why paths are array even the doc use single path?

### ISSUE THREAD

**Issue by pontakornth** [drashland/deno-drash#336]
I can't find any doc about multiple path on same resources. The path variables are even plural. 

```javascript
import { Drash } from "https://deno.land/x/drash@v1.x/mod.ts";

export default class HomeResource extends Drash.Http.Resource {
  static paths = [
    "/([0-9]$)",
  ];

  public GET() {
    this.response.body = "GET request received!";

    return this.response;
  }
}
```

I don't understand this.

**Comment by ebebbington** [comment]
Hey @pontakornth, it's for demonstration purposes too, the paths is a string array to hold every URI that resource to handle, so you can add to it as many times as you want: `static paths = ["/([0-9]$)", "/([0-9]/[0-9]$)", ... 100 more URIs]`

Saying that though, we'll work on adding some extra docs to help clarify this

**Comment by pontakornth** [comment]
@ebebbington Thank you for clarification. I was really confused then. Haha.
