### ISSUE TITLE
Create Drash App on Ubuntu 20.04 error: Uncaught NotFound: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by michaelachrisco** [drashland/deno-drash#350]
**Describe the bug**
I attempted to use the instructions to quick start an api/vue setup as per README instructions. I was given the following error:
```
everyday@everyday:~/my-drash-api$ deno run --allow-read --allow-run --allow-write --allow-net https://deno.land/x/drash/create_app.ts --api
Copy https://deno.land/x/drash/console/create_app/deps.ts contents to:
  /home/everyday/my-drash-api/deps.ts
https://deno.land/x/drash/console/create_app/deps.ts
error: Uncaught NotFound: No such file or directory (os error 2)
    at unwrapResponse (rt/10_dispatch_json.js:25:13)
    at sendSync (rt/10_dispatch_json.js:52:12)
    at opOpenSync (rt/30_files.js:27:12)
    at openSync (rt/30_files.js:43:17)
    at Object.readFileSync (rt/40_read_file.js:8:18)
    at copyFile (https://deno.land/x/drash/create_app.ts:35:25)
    at buildTheBaseline (https://deno.land/x/drash/create_app.ts:121:9)
    at https://deno.land/x/drash/create_app.ts:206:9
everyday@everyday:~/my-drash-api$ wget https://deno.land/x/drash/console/create_app/deps.ts
--2020-07-29 22:17:37--  https://deno.land/x/drash/console/create_app/deps.ts
Resolving deno.land (deno.land)... 2606:4700:3035::6818:6aed, 2606:4700:3034::6818:6bed, 2606:4700:3035::ac43:a3a8, ...
Connecting to deno.land (deno.land)|2606:4700:3035::6818:6aed|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/typescript]
Saving to: ‘deps.ts’

deps.ts                                 [ <=>                                                              ]     146  --.-KB/s    in 0s      

2020-07-29 22:17:38 (1.53 MB/s) - ‘deps.ts’ saved [146]

everyday@everyday:~/my-drash-api$ ls
app.ts  deps.ts
everyday@everyday:~/my-drash-api$ deno run --allow-run --allow-read --allow-write --allow-net https://deno.land/x/drash/create_app.ts --web-app --with-vue
Copy https://deno.land/x/drash/console/create_app/deps.ts contents to:
  /home/everyday/my-drash-api/deps.ts
https://deno.land/x/drash/console/create_app/deps.ts
error: Uncaught NotFound: No such file or directory (os error 2)
    at unwrapResponse (rt/10_dispatch_json.js:25:13)
    at sendSync (rt/10_dispatch_json.js:52:12)
    at opOpenSync (rt/30_files.js:27:12)
    at openSync (rt/30_files.js:43:17)
    at Object.readFileSync (rt/40_read_file.js:8:18)
    at copyFile (https://deno.land/x/drash/create_app.ts:35:25)
    at buildTheBaseline (https://deno.land/x/drash/create_app.ts:121:9)
    at https://deno.land/x/drash/create_app.ts:214:9
```

**To Reproduce**

1. Install deno on new Ubuntu 20.04 system via `curl -fsSL https://deno.land/x/install/install.sh | sh`
2. run `deno run --allow-read --allow-run --allow-write --allow-net https://deno.land/x/drash/create_app.ts --api`
3. Get the above error: 
```
Copy https://deno.land/x/drash/console/create_app/deps.ts contents to:
  /home/everyday/my-drash-api/deps.ts
https://deno.land/x/drash/console/create_app/deps.ts
error: Uncaught NotFound: No such file or directory (os error 2)
```
4. Downloaded deps.ts within the api folder.
5. run `deno run --allow-read --allow-run --allow-write --allow-net https://deno.land/x/drash/create_app.ts --api` Same error

**Expected behavior**
I was hoping to play around with a ful api + vue setup.

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04

Im planning on doing a talk on deno and was hoping to use this package (and oak) as an example of REST APIs. Not sure what im doing wrong here so any help would be appreciated.

**Comment by ebebbington** [comment]
Hi @michaelachrisco , thanks for raising this, we'll look into it

**Comment by michaelachrisco** [comment]
Thanks @crookse and @ebebbington! Ill take a look after work and let you know! 

Should this also apply to Debian as well? Or is Ubuntu only supported for now? I noticed some hard set os values in the code.

**Comment by Guergeiro** [comment]
Hello @michaelachrisco, since we are using deno it's up to the deno maintainers to make sure that their api works in all OS. But since Ubuntu is based on Debian I wouldn't worry about it.

About the hardcoded values, which ones are you skeptical about?

**Comment by michaelachrisco** [comment]
> Hello @michaelachrisco, since we are using deno it's up to the deno maintainers to make sure that their api works in all OS. But since Ubuntu is based on Debian I wouldn't worry about it.
> 
> About the hardcoded values, which ones are you skeptical about?

So I took a second look at hte PR and it was on the Github Workflows, not the actual configuration! Woops...
```yml
      - name: Create App (http nix)
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos')
```

Actual code looks fine!

**Comment by ebebbington** [comment]
@michaelachrisco FYI https://github.com/drashland/deno-drash/releases/tag/v1.2.1

**Comment by crookse** [comment]
@michaelachrisco,

np! You might need to run the script with the `--reload` flag btw. Let us know how it goes. Thanks for bringing this issue to our attention :)

**Comment by michaelachrisco** [comment]
I can confirm its working for ubuntu 20.04 on a VM. Pop OS doesn't seem to work (deno works, just not drash). Its fine.

Thanks everyone!
