### ISSUE TITLE
[QUESTION] How to serve static files inside a mono-repo structure (project/frontend + project/backend)?

### ISSUE THREAD

**Issue by gaylonalfano** [drashland/deno-drash#400]
Hello - Really enjoying the simplicity of Drash. Question regarding serving static files but in the context of a mono-repo project structure:
```
project/backend
.
├── app.ts
├── deps.ts
└── resources
    └── home.resource.ts
```
```
project/frontend
.
└── public
    ├── css
    │   └── index.css
    ├── img
    │   └── logo.png
    ├── js
    │   └── index.js
    └── views
        ├── about
        └── index.html
```
Per the docs (which are *fantastic*!), inside our `app.ts` we configure the `directory` to point to my Drash project (i.e., `project/backend`), and the `static_paths` property to the directories we wish to make public to the client (i.e., `project/frontend/public` in this case). However, I can't get this to work using this sort of mono-repo project structure. [I see you have an open issue regarding virtual paths](https://github.com/drashland/deno-drash/issues/169#issue-598563681) -- would this be the feature I'm looking for? Or is there a simple way that I am not aware of? 

Again, **_I can get it to work just fine using a simple single project directory structure_**. Just curious if/how to do the same using a mono-repo structure. No rush and thank you again for creating such an easy-to-use tool!

**Comment by crookse** [comment]
@gaylonalfano , glad you like the docs! virtual paths may be what you need, but first let me investigate if there's a way to accomplish this. it's been a while since i've touched the static paths code so i don't remember if there's a way

**Comment by ebebbington** [comment]
I believe we had someone ask a similar thing thing on the discord, can't remembber what the response we had was, *but* i don't think it was possible? interested to see what you find @crookse, but FYI we have an issue for the paths issue; #169 

Maybe we could add this in the FAQ for drash docs

**Comment by crookse** [comment]
so i was able to do it, but security is a concern with this implementation because it uses the following config:

```
  directory: Deno.realPathSync("../"),
```

Basically, you're giving users access to your entire `project/` and in my opinion comes with security concerns. Below is the working project if you want to test it out. I do think that we need to push out the virtual paths feature. That way you can specify exactly what directories you want public without having to give users access to your projects entire filesystem.

### Project structure:

```
  ▾ project/
      ▾ back_end/
          app.ts
      ▾ front_end/public/
          style.css
```

### `app.ts`

```typescript
import { Drash } from "https://deno.land/x/drash@v1.2.5/mod.ts";

export default class HomeResource extends Drash.Http.Resource {

  static paths = ["/"];

  public GET() {
    this.response.body = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>Drash</title>
        <link href="/front_end/public/style.css" rel="stylesheet">
      </head>
      <body>
        <h1 class="my-text">This is my title and it is red.</h1>
      </body>
    </html>`;

    return this.response;
  }
}

const server = new Drash.Http.Server({
  directory: Deno.realPathSync("../"),
  resources: [HomeResource],
  response_output: "text/html",
  static_paths: ["/front_end/public"]
});

server.run({
  hostname: "localhost",
  port: 1447
});

console.log("Server running");
```

### `style.css`

```css
.my-text {
    color: #ff0000;
}
```

**Comment by gaylonalfano** [comment]
Thank you for the speedy and detailed response! Thank you @crookse for investigating and demonstrating a potential workaround. I agree with the security concern, so for now I'll stick with the standard project folder structure. Cheers for now!
