### ISSUE TITLE
Address Create App Http Tests Failing For Forks

### ISSUE THREAD

**Issue by ebebbington** [drashland/deno-drash#403]
## Summary

What: Http create app tests fail for for forks. Discuss best way to approach them

**Comment by MVEMCJSUNPE** [comment]
Can't we just use the environment variable "GITHUB_REPOSITORY", which returns the owner and repo in the form of a string `${owner}/{${repo}`? This way, the programmer making the pull request will have the tests run on his/her fork on his/her own repo.

**Comment by ebebbington** [comment]
That might work, feel free to give it a shot :)
