### ISSUE TITLE
[drashland/services] Migrate core loggers to drashland/services

### ISSUE THREAD

**Issue by saragee3** [drashland/deno-drash#429]
## Summary

What:

All core logger pieces should be migrated to the existing logger service in drashland/services.

This includes:
- core_loggers/*
- dictionaries/log_levels.ts
- interfaces/log_level_structure.ts
- interfaces/logger_configs.ts

Why:

Core loggers should be decoupled from drash. Services like Rhum use the logger service.

## Acceptance Criteria

- [ ] Tests

**Comment by saragee3** [comment]
note: Dexter could be _the_ logger (file, console, existing dexter etc merged ... in one..)

**Comment by ebebbington** [comment]
I think that's a really good idea

*One logger to rule them all, one logger to find them, One logger to bring them all, and in the code bind them*

**Comment by crookse** [comment]
closing. this is now in castle.
