### ISSUE TITLE
Create_app is using outdate drash 1.2.3 and doesn't run

### ISSUE THREAD

**Issue by ramonmedeiros** [drashland/deno-drash#432]
## Summary

A clear and concise summary of the bug.

## Steps To Reproduce The Bug

1. Create API from create_app
2. Try to run

## Expected Behavior
```
deno run --allow-net --allow-read --allow-env --allow-write --allow-plugin --unstable drash/app.ts
Check file:///Users/ramon.medeiros/git/ramonmedeiros/learning_deno/drash/app.ts
error: TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  HTTPOptions,
  ~~~~~~~~~~~
```

App run smooth

## Suggested Solution(s)

Fix import modules to use latest version

## Additional Context

Add any other context that will help the project maintainers investigate this issue.

**Comment by ramonmedeiros** [comment]
Where does the create_app get the files from? I can send the PR

**Comment by crookse** [comment]
@ramonmedeiros,

check the console/create_app directory

**Comment by ebebbington** [comment]
I believe this is because you are using the most recent Deno version but your dependencies are out of date in your Drash dir

What’s your Deno version, and what Drash version is your Drash app running

I’m guessing this is down to the Deno version

**Comment by ebebbington** [comment]
Also what Drash version were you using when you ran the update script?

**Comment by MVEMCJSUNPE** [comment]
I agree with @ebebbington . This is probably on an older version of Drash. Using the command, `find . -type f -name *.ts | xargs grep 'HTTPOptions'` on Unix or the command
`gci -Recurse -Include *.ts | sls 'HTTPOptions'` on Windows Powershell, we see that HTTPOptions is used in src/http/server.ts. The import statement 
```ts
import {
  HTTPOptions,
  HTTPSOptions,
  IndexService,
  ISearchResult,
  serve,
  Server as DenoServer,
  ServerRequest,
  serveTLS,
} from "../../deps.ts";
```
imports HTTPOptions from '../../deps.ts'. And if we look at deps.ts, we see the following:
```ts
export type {
  HTTPOptions,
  HTTPSOptions,
  Response,
} from "https://deno.land/std@0.76.0/http/server.ts";
```

So HTTPOptions IS being exported using 'export type'. @ramonmedeiros just needs to checkout the latest version of Drash.

**Comment by crookse** [comment]
@ramonmedeiros,

were you able to resolve your issue(s) with the mentioned solutions?

**Comment by ramonmedeiros** [comment]
Now it's smooth. Thanks
