### ISSUE TITLE
Clean up create_app.ts script tests

### ISSUE THREAD

**Issue by crookse** [drashland/deno-drash#437]
## Summary

What:

Most of the assertions occur in one test case. They should be broken apart into their own test cases.

Why:

We should break out these assertions into their own test cases so that we can debug more easily and faster.

## Acceptance Criteria

Below is a list of tasks that must be completed before this issue can be closed.

- [ ] Refactor create_app.ts script unit tests
- [ ] Tests pass

## Taking on this issue? Read this before you get started.

If you take on this issue and the acceptance criteria does not make sense, post comments on this issue with your questions. Also, you can always hop in the Discord channel at https://discord.gg/c5R3sYuR to get help quickly.

Please read the [Contributing Guidelines](https://github.com/drashland/.github/blob/master/CONTRIBUTING.md) before starting this issue.

**Comment by MVEMCJSUNPE** [comment]
Can I take on this issue?

**Comment by crookse** [comment]
@MVEMCJSUNPE,

yea. want me to assign it to you now?

**Comment by MVEMCJSUNPE** [comment]
Sure.

**Comment by MVEMCJSUNPE** [comment]
I've been working on create_app_test_http.ts, and for some reason, create_app doesn't seem to be creating server.ts when the --api flag is given (this is the command for the third test suite), and I'm kind of having a hard time figuring out why. Running
```
deno run --allow-read --allow-write  --allow-net --allow-run https://raw.githubusercontent.com/drashland/deno-drash/master/create_app.ts --api
```
gives the following output: 
<img width="958" alt="create_app_server" src="https://user-images.githubusercontent.com/10354503/98433227-a8881b80-208a-11eb-9931-022b76ffe7e1.png">
As shown, deps.ts, config.ts, tests/resources/home_resource_test.ts, app.ts, and resources/home_resource.ts, but I can't find any mention of server.ts. However, it seems like create_app almost definitely SHOULD be creating server.ts from line number 196. https://github.com/drashland/deno-drash/blob/d9f15b42843fd3961f5b998a0eba6fe2462b1f70/create_app.ts#L196

**Comment by MVEMCJSUNPE** [comment]
Nvm. create_app_test_http.ts started working for some reason.
