### ISSUE TITLE
[cli] make subcommand

### ISSUE THREAD

**Issue by crookse** [drashland/deno-drash#443]
## Summary

What:

`drash make resource /path/to/resource_file.ts` subcommand

## Acceptance Criteria

Below is a list of tasks that must be completed before this issue can be closed.

- [ ] Write documentation
- [ ] Write unit tests
- [ ] Write integration tests

**Comment by saragee3** [comment]
should we just close these subcommand ones? I closed my pr after our 2021 discussion.

**Comment by crookse** [comment]
@saragee3 yea
