### ISSUE TITLE
Deprecate favicon logic

### ISSUE THREAD

**Issue by crookse** [drashland/deno-drash#451]
## Summary

What:

Deprecate favicon logic.

Why:

Serving the favicon is not part of the core processes of Drash. This logic will be written in the deno-drash-middleware repo under the name `ServeFavicon`.

**Comment by crookse** [comment]
moving this to semester 2 as more planning is needed with drash middleware repo not being able to short-circuit requests in the before_request hook

**Comment by ebebbington** [comment]
removed in v2, now it's handle by a user via a files resource
