### ISSUE TITLE
Deprecate server.static_paths

### ISSUE THREAD

**Issue by crookse** [drashland/deno-drash#454]
## Summary

What:

Deprecate `server.static_paths` config.

Why:

Serving static paths is not part of the core processes of Drash. ~This logic will be written in the deno-drash-middleware repo under the name `ServeStaticPaths`.~

~The logic related to virtual paths will be written in the deno-drash-middleware repo under the name `ServeVirtualPaths`.~

See https://github.com/drashland/deno-drash-middleware/issues/97

**Comment by crookse** [comment]
moving this to semester 2 as more planning is needed with drash middleware repo not being able to short-circuit requests in the before_request hook

**Comment by ebebbington** [comment]
removed in v2
