### ISSUE TITLE
fail to run quickstart

### ISSUE THREAD

**Issue by panov-andy** [drashland/deno-drash#459]
## Summary
Hello,
I was following the tutorial https://drash.land/drash/v1.x/#/#quickstart

## Steps To Reproduce The Bug

```
➜  $ deno run --allow-net app.ts
Check file:///home/awa/_generator/templater/app.ts
error: TS2345 [ERROR]: Argument of type 'unknown' is not assignable to parameter of type 'string'.
        return engine.render(args[0], data);
                             ~~~~~~~
    at https://deno.land/x/drash@v1.3.0/src/http/response.ts:141:30

➜  $ deno --version
deno 1.6.0 (release, x86_64-unknown-linux-gnu)
v8 8.8.278.2
typescript 4.1.2
```
```app.ts
import { Drash } from "https://deno.land/x/drash@v1.3.0/mod.ts";

class HomeResource extends Drash.Http.Resource {
  static paths = ["/"];
  public GET() {
    this.response.body = "Hello World!";
    return this.response;
  }
}

const server = new Drash.Http.Server({
  response_output: "text/html",
  resources: [HomeResource]
});

server.run({
  hostname: "localhost",
  port: 1447
});

```

## Additional Context

Ubuntu 18.04

**Comment by ebebbington** [comment]
@panov-andy We haven't updated following the most recent deno release so deno v1.6.0 doesn't work with drash v1.3.0. We'll work on a new release that is deno 1.6.0 compatible, for now, you'll have to downgrade to deno v1.5.4

**Comment by ebebbington** [comment]
@panov-andy  v1.3.1 has been released with this fix - the version number isn't updated on https://drash.land yet but you can just update the drash version of your import, and everything should work fine with deno v1.6.0

Let me know if it does fix the issue, just to be sure :)

**Comment by panov-andy** [comment]
Thank you.
It works now.
