### ISSUE TITLE
How to send binary body?

### ISSUE THREAD

**Issue by juzi5201314** [drashland/deno-drash#491]
## Summary
Such as responding to a document?
```
this.response.body = (await Deno.readFile("test.png"));
```
This will get a null.

**Comment by ebebbington** [comment]
Hey @juzi5201314, we don't actually support responding with typed arrays, for the time being you could decode it first:

```ts
const rawContent = await Deno.readFile("test.png")
const decodedContent = new TextDecoder().decode(rawContent)
this.response.body = decodedContent
```

Then re-encode it on the client

At the moment we return `"null"` if the data type is a `UInt8Array`, but I think this is something we should support

Can i ask why you're trying to respond with the binary data of an image?

**Comment by juzi5201314** [comment]
> Hey @juzi5201314, we don't actually support responding with typed arrays, for the time being you could decode it first:
> 
> ```ts
> const rawContent = await Deno.readFile("test.png")
> const decodedContent = new TextDecoder().decode(rawContent)
> this.response.body = decodedContent
> ```
> 
> Then re-encode it on the client
> 
> At the moment we return `"null"` if the data type is a `UInt8Array`, but I think this is something we should support
> 
> Can i ask why you're trying to respond with the binary data of an image?

okay, thank you.
The binary data response of the image is because I need to generate a picture based on the input.

**Comment by ebebbington** [comment]
Ah ok, well I think we should keep this issue open to track adding the support

**Comment by crookse** [comment]
i agree with this @juzi5201314. we'll investigate. it might be that we already have the logic to do this, but it's just not made available for public use. stay tuned!

**Comment by juzi5201314** [comment]
I try to simply support it. #492
