### ISSUE TITLE
drash.land seems to be down

### ISSUE THREAD

**Issue by closet6** [drashland/deno-drash#499]

**Comment by Guergeiro** [comment]
Yes it is. We are working on it.
For more information, please visit our discord server.

**Comment by crookse** [comment]
Hey @closet6, we're currently provisioning the server right now, but yea like @Guergeiro said, more info on in the Discord.

**Comment by crookse** [comment]
@closet6, site is up

**Comment by closet6** [comment]
@crookse awesome thx
