### ISSUE TITLE
Create App script

### ISSUE THREAD

**Issue by crookse** [drashland/deno-drash#514]
## Summary

What:

Implement the Create App script in the `cli.ts` file.

## Acceptance Criteria

Below is a list of tasks that must be completed before this issue can be closed.

- [ ] Write documentation
- [ ] Write unit tests
- [ ] Write integration tests
- [ ] `cli.ts` uses drashland/line
- [ ] command should be `drash create-app --options --and --args`
- [ ] command should be able to scaffold a vue app
- [ ] command should be able to scaffold a react app
- [ ] command should be able to scaffold an API app
- [ ] command should be able to scaffold a basic web app that doesn't use a front-end framework

**Comment by ebebbington** [comment]
closing, see #395
