### ISSUE TITLE
Clean up errors logic

### ISSUE THREAD

**Issue by crookse** [drashland/deno-drash#516]
## Summary

What:

Search for `TODO-ERRORS` to see what work needs to be done.

## Acceptance Criteria

Below is a list of tasks that must be completed before this issue can be closed.

- [ ] There is a `TODO-ERRORS Document the error codes in the website`. Just make sure there is an issue in the website repo to document the error codes.
- [ ] Write integration tests
- [ ] Write unit tests

**Comment by ebebbington** [comment]
drash error is no longer a thing
